### ISSUE TITLE
Support GraphQL SDL via stdin

### ISSUE THREAD

**Issue by NathanRSmith** [sheerun/graphqlviz#22]
Currently, JSON can be piped via stdin if no address/file is specified. After discussion in #21, it was determined that it would be good to support parsing the GraphQL SDL format as well if the `--graphql` flag is present.

**Comment by sheerun** [comment]
Implemented in 3.1.0 by auto-detecting if graphql schema is passed

**Comment by robross0606** [comment]
Sadly this doesn't quite do what I had expected.  
```
cat src/graphql/schema/**/*.graphql | graphqlviz -g | dot -Tpng > doc/schema.png
```
The problem comes in when multiple modular schema files declare portions of the `query`, `mutation` or `subscription` types.  A tool like [merge-graphql-schemas](https://github.com/Urigo/merge-graphql-schemas) will merge those into a single graphql schema.  However, simply `cat`'ing the files results in errors on your tool like:
```
There can be only one type named "Query".
There can be only one type named "Query".
There can be only one type named "Query".
There can be only one type named "Mutation".
```
Sadly, in order for this to really work as I had hoped, `graphqlviz` would need to directly accept a glob pattern for the graphql and run it through [merge-graphql-schemas](https://github.com/Urigo/merge-graphql-schemas) before processing.  Using `stdin` won't cut it for a truly modular schema.

**Comment by LaloHao** [comment]
You can use the input file `/dev/stdin`

`cat *.gql | graphqlviz /dev/stdin | tee schema.dot >(dot -Tpng -o schema.png)`

Or your exact command

`cat src/graphql/schema/**/*.graphql | graphqlviz /dev/stdin | dot -Tpng > doc/schema.png`

**Comment by robross0606** [comment]
@LaloHao I already explained above why that doesn't work.
